#############################################################################
# Makefile for building: stray68K
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  ../stray68K.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ../stray68K.pro -spec linux-g++ CONFIG+=debug CONFIG-=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../../stray68K -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = stray68K1.0.0
DISTDIR = $(OBJECTS_DIR)/.tmp/stray68K1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip
ROOT_DIR      := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

####### Output directory

OBJECTS_DIR   = objects
BUILD_DIR     = build
ASSEMBLER_DIR = $(ROOT_DIR)/src/assembler
EMULATOR_DIR  = $(ROOT_DIR)/src/emulator
UI_DIR	      = $(ROOT_DIR)/src/ui
SOURCE_DIR    = $(ROOT_DIR)/src

####### Files

SOURCES       = $(EMULATOR_DIR)/emulator.c \
		$(ASSEMBLER_DIR)/assembler.c \
		$(ASSEMBLER_DIR)/dictionary.c \
		$(ASSEMBLER_DIR)/lexical.c \
		$(ASSEMBLER_DIR)/semantic.c \
		$(ASSEMBLER_DIR)/strcmpci.c \
		$(ASSEMBLER_DIR)/syntactic.c \
		$(EMULATOR_DIR)/cpu.c \
		$(EMULATOR_DIR)/handler.c \
		$(EMULATOR_DIR)/ram.c \
		$(EMULATOR_DIR)/utils.c \
		$(SOURCE_DIR)/main.cpp \
		$(UI_DIR)/Completer/completer.cpp \
		$(UI_DIR)/Completer/completeritem.cpp \
		$(UI_DIR)/Completer/completerparser.cpp \
		$(UI_DIR)/axolotlApp.cpp \
		$(UI_DIR)/configmanager.cpp \
		$(UI_DIR)/editor.cpp \
		$(UI_DIR)/editorhighlighter.cpp \
		$(UI_DIR)/fileoptions.cpp \
		$(UI_DIR)/outputhighlighter.cpp \
		$(UI_DIR)/projectmanager.cpp \
		$(UI_DIR)/projecttreeitem.cpp \
		$(UI_DIR)/projectwizard.cpp \
		$(UI_DIR)/promanager.cpp \
		$(UI_DIR)/settingsmanager.cpp \
		$(UI_DIR)/sourceadder.cpp \
		$(UI_DIR)/themesetter.cpp \
		$(UI_DIR)/uimemory.cpp \
		$(UI_DIR)/uistack.cpp \
		$(OBJECTS_DIR)/qrc_iconPack.cpp \
		$(OBJECTS_DIR)/qrc_suggestions.cpp \
		$(OBJECTS_DIR)/qrc_theme.cpp \
		$(OBJECTS_DIR)/moc_completer.cpp \
		$(OBJECTS_DIR)/moc_completerparser.cpp \
		$(OBJECTS_DIR)/moc_axolotlApp.cpp \
		$(OBJECTS_DIR)/moc_editor.cpp \
		$(OBJECTS_DIR)/moc_editorhighlighter.cpp \
		$(OBJECTS_DIR)/moc_fileoptions.cpp \
		$(OBJECTS_DIR)/moc_outputhighlighter.cpp \
		$(OBJECTS_DIR)/moc_projectmanager.cpp \
		$(OBJECTS_DIR)/moc_projecttreeitem.cpp \
		$(OBJECTS_DIR)/moc_projectwizard.cpp \
		$(OBJECTS_DIR)/moc_settingsmanager.cpp \
		$(OBJECTS_DIR)/moc_sourceadder.cpp \
		$(OBJECTS_DIR)/moc_uimemory.cpp \
		$(OBJECTS_DIR)/moc_uistack.cpp

OBJECTS       = $(OBJECTS_DIR)/assembler.o \
		$(OBJECTS_DIR)/dictionary.o \
		$(OBJECTS_DIR)/lexical.o \
		$(OBJECTS_DIR)/semantic.o \
		$(OBJECTS_DIR)/strcmpci.o \
		$(OBJECTS_DIR)/syntactic.o \
		$(OBJECTS_DIR)/JSON.o \
		$(OBJECTS_DIR)/cpu.o \
		$(OBJECTS_DIR)/emulator.o \
		$(OBJECTS_DIR)/handler.o \
		$(OBJECTS_DIR)/ram.o \
		$(OBJECTS_DIR)/utils.o \
		$(OBJECTS_DIR)/main.o \
		$(OBJECTS_DIR)/completer.o \
		$(OBJECTS_DIR)/completeritem.o \
		$(OBJECTS_DIR)/completerparser.o \
		$(OBJECTS_DIR)/axolotlApp.o \
		$(OBJECTS_DIR)/configmanager.o \
		$(OBJECTS_DIR)/editor.o \
		$(OBJECTS_DIR)/editorhighlighter.o \
		$(OBJECTS_DIR)/fileoptions.o \
		$(OBJECTS_DIR)/outputhighlighter.o \
		$(OBJECTS_DIR)/projectmanager.o \
		$(OBJECTS_DIR)/projecttreeitem.o \
		$(OBJECTS_DIR)/projectwizard.o \
		$(OBJECTS_DIR)/promanager.o \
		$(OBJECTS_DIR)/settingsmanager.o \
		$(OBJECTS_DIR)/sourceadder.o \
		$(OBJECTS_DIR)/themesetter.o \
		$(OBJECTS_DIR)/uimemory.o \
		$(OBJECTS_DIR)/uistack.o \
		$(OBJECTS_DIR)/qrc_iconPack.o \
		$(OBJECTS_DIR)/qrc_suggestions.o \
		$(OBJECTS_DIR)/qrc_theme.o \
		$(OBJECTS_DIR)/moc_completer.o \
		$(OBJECTS_DIR)/moc_completerparser.o \
		$(OBJECTS_DIR)/moc_axolotlApp.o \
		$(OBJECTS_DIR)/moc_editor.o \
		$(OBJECTS_DIR)/moc_editorhighlighter.o \
		$(OBJECTS_DIR)/moc_fileoptions.o \
		$(OBJECTS_DIR)/moc_outputhighlighter.o \
		$(OBJECTS_DIR)/moc_projectmanager.o \
		$(OBJECTS_DIR)/moc_projecttreeitem.o \
		$(OBJECTS_DIR)/moc_projectwizard.o \
		$(OBJECTS_DIR)/moc_settingsmanager.o \
		$(OBJECTS_DIR)/moc_sourceadder.o \
		$(OBJECTS_DIR)/moc_uimemory.o \
		$(OBJECTS_DIR)/moc_uistack.o
		
DIST          = $(UI_DIR)/Completer/completer.pri \
		$(UI_DIR)/README.md \
		$(UI_DIR)/config.json \
		$(UI_DIR)/img/close.png \
		$(UI_DIR)/img/file.png \
		$(UI_DIR)/img/fileicon.png \
		$(UI_DIR)/img/folder.png \
		$(UI_DIR)/img/method.png \
		$(UI_DIR)/img/nativeKeyword.png \
		$(UI_DIR)/img/newfile.png \
		$(UI_DIR)/img/newproj.png \
		$(UI_DIR)/img/open.png \
		$(UI_DIR)/img/param.png \
		$(UI_DIR)/img/project.png \
		$(UI_DIR)/img/red_x.png \
		$(UI_DIR)/img/redo.png \
		$(UI_DIR)/img/run.png \
		$(UI_DIR)/img/save.png \
		$(UI_DIR)/img/settings.png \
		$(UI_DIR)/img/shebang.png \
		$(UI_DIR)/img/splash.jpg \
		$(UI_DIR)/img/undo.png \
		$(UI_DIR)/img/zoomin.png \
		$(UI_DIR)/img/zoomout.png \
		$(UI_DIR)/keywords/directives \
		$(UI_DIR)/keywords/keywords \
		$(UI_DIR)/keywords/methods \
		$(UI_DIR)/keywords/regs \
		$(UI_DIR)/keywords/shebang \
		$(UI_DIR)/recent_files \
		$(UI_DIR)/recent_projects \
		$(UI_DIR)/theme/DarkTheme.json \
		$(UI_DIR)/theme/LightTheme.json \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		stray68K.pro $(ASSEMBLER_DIR)/assembler.h \
		$(ASSEMBLER_DIR)/clowncommon.h \
		$(ASSEMBLER_DIR)/dictionary.h \
		$(ASSEMBLER_DIR)/lexical.h \
		$(ASSEMBLER_DIR)/lexical.l \
		$(ASSEMBLER_DIR)/semantic.h \
		$(ASSEMBLER_DIR)/strcmpci.h \
		$(ASSEMBLER_DIR)/syntactic.h \
		$(ASSEMBLER_DIR)/syntactic.y \
		$(EMULATOR_DIR)/JSON.h \
		$(EMULATOR_DIR)/cpu.h \
		$(EMULATOR_DIR)/emulator.h \
		$(EMULATOR_DIR)/enums.h \
		$(EMULATOR_DIR)/handler.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(EMULATOR_DIR)/ram.h \
		$(SOURCE_DIR)/stray_m68k.h \
		$(EMULATOR_DIR)/utils.h \
		$(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completeritem.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(UI_DIR)/axolotlApp.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/editor.h \
		$(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/fileoptions.h \
		$(UI_DIR)/outputhighlighter.h \
		$(UI_DIR)/projectmanager.h \
		$(UI_DIR)/projecttreeitem.h \
		$(UI_DIR)/projectwizard.h \
		$(UI_DIR)/promanager.h \
		$(UI_DIR)/settingsmanager.h \
		$(UI_DIR)/sourceadder.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/uimemory.h \
		$(UI_DIR)/uistack.h $(ASSEMBLER_DIR)/assembler.c \
		$(ASSEMBLER_DIR)/dictionary.c \
		$(ASSEMBLER_DIR)/lexical.c \
		$(ASSEMBLER_DIR)/semantic.c \
		$(ASSEMBLER_DIR)/strcmpci.c \
		$(ASSEMBLER_DIR)/syntactic.c \
		$(EMULATOR_DIR)/JSON.c \
		$(EMULATOR_DIR)/cpu.c \
		$(EMULATOR_DIR)/emulator.c \
		$(EMULATOR_DIR)/handler.c \
		$(EMULATOR_DIR)/ram.c \
		$(EMULATOR_DIR)/utils.c \
		$(SOURCE_DIR)/main.cpp \
		$(UI_DIR)/Completer/completer.cpp \
		$(UI_DIR)/Completer/completeritem.cpp \
		$(UI_DIR)/Completer/completerparser.cpp \
		$(UI_DIR)/axolotlApp.cpp \
		$(UI_DIR)/configmanager.cpp \
		$(UI_DIR)/editor.cpp \
		$(UI_DIR)/editorhighlighter.cpp \
		$(UI_DIR)/fileoptions.cpp \
		$(UI_DIR)/outputhighlighter.cpp \
		$(UI_DIR)/projectmanager.cpp \
		$(UI_DIR)/projecttreeitem.cpp \
		$(UI_DIR)/projectwizard.cpp \
		$(UI_DIR)/promanager.cpp \
		$(UI_DIR)/settingsmanager.cpp \
		$(UI_DIR)/sourceadder.cpp \
		$(UI_DIR)/themesetter.cpp \
		$(UI_DIR)/uimemory.cpp \
		$(UI_DIR)/uistack.cpp
QMAKE_TARGET  = $(BUILD_DIR)/stray68K
DESTDIR       = 
TARGET        = $(BUILD_DIR)/stray68K


first: object_dir build_dir all
####### Build rules

$(BUILD_DIR)/stray68K: $(OBJECTS_DIR)/ui_completer.h $(OBJECTS_DIR)/ui_axolotlApp.h $(OBJECTS_DIR)/ui_fileoptions.h $(OBJECTS_DIR)/ui_projectwizard.h $(OBJECTS_DIR)/ui_settingsmanager.h $(OBJECTS_DIR)/ui_sourceadder.h $(OBJECTS_DIR)/ui_uimemory.h $(OBJECTS_DIR)/ui_uistack.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: stray68K.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		stray68K.pro \
		$(UI_DIR)/iconPack.qrc \
		$(UI_DIR)/suggestions.qrc \
		$(UI_DIR)/theme.qrc
	$(QMAKE) -o Makefile stray68K.pro -spec linux-g++ CONFIG+=debug CONFIG-=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
stray68K.pro:
$(UI_DIR)/iconPack.qrc:
$(UI_DIR)/suggestions.qrc:
$(UI_DIR)/theme.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile stray68K.pro -spec linux-g++ CONFIG+=debug CONFIG-=qml_debug

qmake_all: FORCE


object_dir:
	@$(MKDIR) objects

build_dir:
	@$(MKDIR) build


all: Makefile $(BUILD_DIR)/stray68K copy

copy:
	$(COPY_FILE) $(UI_DIR)/config.json $(BUILD_DIR)/
	$(COPY_FILE) -r $(UI_DIR)/theme $(BUILD_DIR)/

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents $(UI_DIR)/iconPack.qrc $(UI_DIR)/suggestions.qrc $(UI_DIR)/theme.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents $(ASSEMBLER_DIR)/assembler.h $(ASSEMBLER_DIR)/clowncommon.h $(ASSEMBLER_DIR)/dictionary.h $(ASSEMBLER_DIR)/lexical.h $(ASSEMBLER_DIR)/lexical.l $(ASSEMBLER_DIR)/semantic.h $(ASSEMBLER_DIR)/strcmpci.h $(ASSEMBLER_DIR)/syntactic.h $(ASSEMBLER_DIR)/syntactic.y $(EMULATOR_DIR)/JSON.h $(EMULATOR_DIR)/cpu.h $(EMULATOR_DIR)/emulator.h $(EMULATOR_DIR)/enums.h $(EMULATOR_DIR)/handler.h $(EMULATOR_DIR)/motorolatypes.h $(EMULATOR_DIR)/ram.h $(SOURCE_DIR)/stray_m68k.h $(EMULATOR_DIR)/utils.h $(UI_DIR)/Completer/completer.h $(UI_DIR)/Completer/completerenums.h $(UI_DIR)/Completer/completeritem.h $(UI_DIR)/Completer/completerparser.h $(UI_DIR)/Completer/completerstructs.h $(UI_DIR)/axolotlApp.h $(UI_DIR)/configmanager.h $(UI_DIR)/editor.h $(UI_DIR)/editorhighlighter.h $(UI_DIR)/fileoptions.h $(UI_DIR)/outputhighlighter.h $(UI_DIR)/projectmanager.h $(UI_DIR)/projecttreeitem.h $(UI_DIR)/projectwizard.h $(UI_DIR)/promanager.h $(UI_DIR)/settingsmanager.h $(UI_DIR)/sourceadder.h $(UI_DIR)/themesetter.h $(UI_DIR)/uimemory.h $(UI_DIR)/uistack.h $(DISTDIR)/
	$(COPY_FILE) --parents $(ASSEMBLER_DIR)/assembler.c $(ASSEMBLER_DIR)/dictionary.c $(ASSEMBLER_DIR)/lexical.c $(ASSEMBLER_DIR)/semantic.c $(ASSEMBLER_DIR)/strcmpci.c $(ASSEMBLER_DIR)/syntactic.c $(EMULATOR_DIR)/JSON.c $(EMULATOR_DIR)/cpu.c $(EMULATOR_DIR)/emulator.c $(EMULATOR_DIR)/handler.c $(EMULATOR_DIR)/ram.c $(EMULATOR_DIR)/utils.c $(SOURCE_DIR)/main.cpp $(UI_DIR)/Completer/completer.cpp $(UI_DIR)/Completer/completeritem.cpp $(UI_DIR)/Completer/completerparser.cpp $(UI_DIR)/axolotlApp.cpp $(UI_DIR)/configmanager.cpp $(UI_DIR)/editor.cpp $(UI_DIR)/editorhighlighter.cpp $(UI_DIR)/fileoptions.cpp $(UI_DIR)/outputhighlighter.cpp $(UI_DIR)/projectmanager.cpp $(UI_DIR)/projecttreeitem.cpp $(UI_DIR)/projectwizard.cpp $(UI_DIR)/promanager.cpp $(UI_DIR)/settingsmanager.cpp $(UI_DIR)/sourceadder.cpp $(UI_DIR)/themesetter.cpp $(UI_DIR)/uimemory.cpp $(UI_DIR)/uistack.cpp $(DISTDIR)/
	$(COPY_FILE) --parents $(UI_DIR)/Completer/completer.ui $(UI_DIR)/axolotlApp.ui $(UI_DIR)/fileoptions.ui $(UI_DIR)/projectwizard.ui $(UI_DIR)/settingsmanager.ui $(UI_DIR)/sourceadder.ui $(UI_DIR)/uimemory.ui $(UI_DIR)/uistack.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) -r $(BUILD_DIR) $(OBJECTS_DIR)


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: $(OBJECTS_DIR)/qrc_iconPack.cpp $(OBJECTS_DIR)/qrc_suggestions.cpp $(OBJECTS_DIR)/qrc_theme.cpp
compiler_rcc_clean:
	-$(DEL_FILE) $(OBJECTS_DIR)/qrc_iconPack.cpp $(OBJECTS_DIR)/qrc_suggestions.cpp $(OBJECTS_DIR)/qrc_theme.cpp
$(OBJECTS_DIR)/qrc_iconPack.cpp: $(UI_DIR)/iconPack.qrc \
		/usr/lib/qt5/bin/rcc \
		$(UI_DIR)/img/open.png \
		$(UI_DIR)/img/shebang.png \
		$(UI_DIR)/img/close.png \
		$(UI_DIR)/img/newproj.png \
		$(UI_DIR)/img/folder.png \
		$(UI_DIR)/img/method.png \
		$(UI_DIR)/img/fileicon.png \
		$(UI_DIR)/img/param.png \
		$(UI_DIR)/img/splash.jpg \
		$(UI_DIR)/img/newfile.png \
		$(UI_DIR)/img/settings.png \
		$(UI_DIR)/img/file.png \
		$(UI_DIR)/img/zoomin.png \
		$(UI_DIR)/img/zoomout.png \
		$(UI_DIR)/img/B68.png \
		$(UI_DIR)/img/red_x.png \
		$(UI_DIR)/img/run.png \
		$(UI_DIR)/img/save.png \
		$(UI_DIR)/img/project.png \
		$(UI_DIR)/img/s68k.png \
		$(UI_DIR)/img/nativeKeyword.png
	/usr/lib/qt5/bin/rcc -name iconPack $(UI_DIR)/iconPack.qrc -o $(OBJECTS_DIR)/qrc_iconPack.cpp

$(OBJECTS_DIR)/qrc_suggestions.cpp: $(UI_DIR)/suggestions.qrc \
		/usr/lib/qt5/bin/rcc \
		$(UI_DIR)/keywords/regs \
		$(UI_DIR)/keywords/directives \
		$(UI_DIR)/keywords/keywords
	/usr/lib/qt5/bin/rcc -name suggestions $(UI_DIR)/suggestions.qrc -o $(OBJECTS_DIR)/qrc_suggestions.cpp

$(OBJECTS_DIR)/qrc_theme.cpp: $(UI_DIR)/theme.qrc \
		/usr/lib/qt5/bin/rcc \
		$(UI_DIR)/theme/LightTheme.json \
		$(UI_DIR)/theme/DarkTheme.json
	/usr/lib/qt5/bin/rcc -name theme $(UI_DIR)/theme.qrc -o $(OBJECTS_DIR)/qrc_theme.cpp

compiler_moc_predefs_make_all: $(OBJECTS_DIR)/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) $(OBJECTS_DIR)/moc_predefs.h
$(OBJECTS_DIR)/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o $(OBJECTS_DIR)/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: $(OBJECTS_DIR)/moc_completer.cpp $(OBJECTS_DIR)/moc_completerparser.cpp $(OBJECTS_DIR)/moc_axolotlApp.cpp $(OBJECTS_DIR)/moc_editor.cpp $(OBJECTS_DIR)/moc_editorhighlighter.cpp $(OBJECTS_DIR)/moc_fileoptions.cpp $(OBJECTS_DIR)/moc_outputhighlighter.cpp $(OBJECTS_DIR)/moc_projectmanager.cpp $(OBJECTS_DIR)/moc_projecttreeitem.cpp $(OBJECTS_DIR)/moc_projectwizard.cpp $(OBJECTS_DIR)/moc_settingsmanager.cpp $(OBJECTS_DIR)/moc_sourceadder.cpp $(OBJECTS_DIR)/moc_uimemory.cpp $(OBJECTS_DIR)/moc_uistack.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) $(OBJECTS_DIR)/moc_completer.cpp $(OBJECTS_DIR)/moc_completerparser.cpp $(OBJECTS_DIR)/moc_axolotlApp.cpp $(OBJECTS_DIR)/moc_editor.cpp $(OBJECTS_DIR)/moc_editorhighlighter.cpp $(OBJECTS_DIR)/moc_fileoptions.cpp $(OBJECTS_DIR)/moc_outputhighlighter.cpp $(OBJECTS_DIR)/moc_projectmanager.cpp $(OBJECTS_DIR)/moc_projecttreeitem.cpp $(OBJECTS_DIR)/moc_projectwizard.cpp $(OBJECTS_DIR)/moc_settingsmanager.cpp $(OBJECTS_DIR)/moc_sourceadder.cpp $(OBJECTS_DIR)/moc_uimemory.cpp $(OBJECTS_DIR)/moc_uistack.cpp
$(OBJECTS_DIR)/moc_completer.cpp: $(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/Completer/completer.h -o $(OBJECTS_DIR)/moc_completer.cpp

$(OBJECTS_DIR)/moc_completerparser.cpp: $(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/Completer/completerparser.h -o $(OBJECTS_DIR)/moc_completerparser.cpp

$(OBJECTS_DIR)/moc_axolotlApp.cpp: $(UI_DIR)/axolotlApp.h \
		$(UI_DIR)/editor.h \
		$(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(UI_DIR)/projectwizard.h \
		$(UI_DIR)/promanager.h \
		$(UI_DIR)/outputhighlighter.h \
		$(UI_DIR)/projectmanager.h \
		$(UI_DIR)/projecttreeitem.h \
		$(UI_DIR)/sourceadder.h \
		$(UI_DIR)/fileoptions.h \
		$(UI_DIR)/settingsmanager.h \
		$(UI_DIR)/uimemory.h \
		$(UI_DIR)/uistack.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/axolotlApp.h -o $(OBJECTS_DIR)/moc_axolotlApp.cpp

$(OBJECTS_DIR)/moc_editor.cpp: $(UI_DIR)/editor.h \
		$(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/editor.h -o $(OBJECTS_DIR)/moc_editor.cpp

$(OBJECTS_DIR)/moc_editorhighlighter.cpp: $(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/editorhighlighter.h -o $(OBJECTS_DIR)/moc_editorhighlighter.cpp

$(OBJECTS_DIR)/moc_fileoptions.cpp: $(UI_DIR)/fileoptions.h \
		$(UI_DIR)/promanager.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/fileoptions.h -o $(OBJECTS_DIR)/moc_fileoptions.cpp

$(OBJECTS_DIR)/moc_outputhighlighter.cpp: $(UI_DIR)/outputhighlighter.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/outputhighlighter.h -o $(OBJECTS_DIR)/moc_outputhighlighter.cpp

$(OBJECTS_DIR)/moc_projectmanager.cpp: $(UI_DIR)/projectmanager.h \
		$(UI_DIR)/projecttreeitem.h \
		$(UI_DIR)/promanager.h \
		$(UI_DIR)/sourceadder.h \
		$(UI_DIR)/fileoptions.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/projectmanager.h -o $(OBJECTS_DIR)/moc_projectmanager.cpp

$(OBJECTS_DIR)/moc_projecttreeitem.cpp: $(UI_DIR)/projecttreeitem.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/projecttreeitem.h -o $(OBJECTS_DIR)/moc_projecttreeitem.cpp

$(OBJECTS_DIR)/moc_projectwizard.cpp: $(UI_DIR)/projectwizard.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/promanager.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/projectwizard.h -o $(OBJECTS_DIR)/moc_projectwizard.cpp

$(OBJECTS_DIR)/moc_settingsmanager.cpp: $(UI_DIR)/settingsmanager.h \
		$(UI_DIR)/configmanager.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/settingsmanager.h -o $(OBJECTS_DIR)/moc_settingsmanager.cpp

$(OBJECTS_DIR)/moc_sourceadder.cpp: $(UI_DIR)/sourceadder.h \
		$(UI_DIR)/promanager.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/sourceadder.h -o $(OBJECTS_DIR)/moc_sourceadder.cpp

$(OBJECTS_DIR)/moc_uimemory.cpp: $(UI_DIR)/uimemory.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/uimemory.h -o $(OBJECTS_DIR)/moc_uimemory.cpp

$(OBJECTS_DIR)/moc_uistack.cpp: $(UI_DIR)/uistack.h \
		$(OBJECTS_DIR)/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include $(OBJECTS_DIR)/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I$(BUILD_DIR)/stray68K -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include $(UI_DIR)/uistack.h -o $(OBJECTS_DIR)/moc_uistack.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: $(OBJECTS_DIR)/ui_completer.h $(OBJECTS_DIR)/ui_axolotlApp.h $(OBJECTS_DIR)/ui_fileoptions.h $(OBJECTS_DIR)/ui_projectwizard.h $(OBJECTS_DIR)/ui_settingsmanager.h $(OBJECTS_DIR)/ui_sourceadder.h $(OBJECTS_DIR)/ui_uimemory.h $(OBJECTS_DIR)/ui_uistack.h
compiler_uic_clean:
	-$(DEL_FILE) $(OBJECTS_DIR)/ui_completer.h $(OBJECTS_DIR)/ui_axolotlApp.h $(OBJECTS_DIR)/ui_fileoptions.h $(OBJECTS_DIR)/ui_projectwizard.h $(OBJECTS_DIR)/ui_settingsmanager.h $(OBJECTS_DIR)/ui_sourceadder.h $(OBJECTS_DIR)/ui_uimemory.h $(OBJECTS_DIR)/ui_uistack.h
$(OBJECTS_DIR)/ui_completer.h: $(UI_DIR)/Completer/completer.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/Completer/completer.ui -o $(OBJECTS_DIR)/ui_completer.h

$(OBJECTS_DIR)/ui_axolotlApp.h: $(UI_DIR)/axolotlApp.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/axolotlApp.ui -o $(OBJECTS_DIR)/ui_axolotlApp.h

$(OBJECTS_DIR)/ui_fileoptions.h: $(UI_DIR)/fileoptions.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/fileoptions.ui -o $(OBJECTS_DIR)/ui_fileoptions.h

$(OBJECTS_DIR)/ui_projectwizard.h: $(UI_DIR)/projectwizard.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/projectwizard.ui -o $(OBJECTS_DIR)/ui_projectwizard.h

$(OBJECTS_DIR)/ui_settingsmanager.h: $(UI_DIR)/settingsmanager.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/settingsmanager.ui -o $(OBJECTS_DIR)/ui_settingsmanager.h

$(OBJECTS_DIR)/ui_sourceadder.h: $(UI_DIR)/sourceadder.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/sourceadder.ui -o $(OBJECTS_DIR)/ui_sourceadder.h

$(OBJECTS_DIR)/ui_uimemory.h: $(UI_DIR)/uimemory.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/uimemory.ui -o $(OBJECTS_DIR)/ui_uimemory.h

$(OBJECTS_DIR)/ui_uistack.h: $(UI_DIR)/uistack.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic $(UI_DIR)/uistack.ui -o $(OBJECTS_DIR)/ui_uistack.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

$(OBJECTS_DIR)/assembler.o: $(ASSEMBLER_DIR)/assembler.c $(ASSEMBLER_DIR)/assembler.h \
		$(ASSEMBLER_DIR)/clowncommon.h \
		$(ASSEMBLER_DIR)/semantic.h \
		$(ASSEMBLER_DIR)/syntactic.h \
		$(EMULATOR_DIR)/JSON.h \
		$(EMULATOR_DIR)/motorolatypes.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/assembler.o $(ASSEMBLER_DIR)/assembler.c

$(OBJECTS_DIR)/dictionary.o: $(ASSEMBLER_DIR)/dictionary.c $(ASSEMBLER_DIR)/dictionary.h \
		$(ASSEMBLER_DIR)/clowncommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/dictionary.o $(ASSEMBLER_DIR)/dictionary.c

$(OBJECTS_DIR)/lexical.o: $(ASSEMBLER_DIR)/lexical.c $(ASSEMBLER_DIR)/syntactic.h \
		$(ASSEMBLER_DIR)/clowncommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/lexical.o $(ASSEMBLER_DIR)/lexical.c

$(OBJECTS_DIR)/semantic.o: $(ASSEMBLER_DIR)/semantic.c $(ASSEMBLER_DIR)/semantic.h \
		$(ASSEMBLER_DIR)/clowncommon.h \
		$(ASSEMBLER_DIR)/syntactic.h \
		$(EMULATOR_DIR)/JSON.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(ASSEMBLER_DIR)/dictionary.h \
		$(ASSEMBLER_DIR)/strcmpci.h \
		$(ASSEMBLER_DIR)/lexical.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/semantic.o $(ASSEMBLER_DIR)/semantic.c

$(OBJECTS_DIR)/strcmpci.o: $(ASSEMBLER_DIR)/strcmpci.c $(ASSEMBLER_DIR)/strcmpci.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/strcmpci.o $(ASSEMBLER_DIR)/strcmpci.c

$(OBJECTS_DIR)/syntactic.o: $(ASSEMBLER_DIR)/syntactic.c $(ASSEMBLER_DIR)/syntactic.h \
		$(ASSEMBLER_DIR)/clowncommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/syntactic.o $(ASSEMBLER_DIR)/syntactic.c

$(OBJECTS_DIR)/JSON.o: $(EMULATOR_DIR)/JSON.c $(EMULATOR_DIR)/JSON.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(EMULATOR_DIR)/cpu.h \
		$(EMULATOR_DIR)/handler.h \
		$(EMULATOR_DIR)/enums.h \
		$(EMULATOR_DIR)/utils.h \
		$(EMULATOR_DIR)/ram.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/JSON.o $(EMULATOR_DIR)/JSON.c

$(OBJECTS_DIR)/cpu.o: $(EMULATOR_DIR)/cpu.c $(EMULATOR_DIR)/cpu.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(EMULATOR_DIR)/handler.h \
		$(EMULATOR_DIR)/enums.h \
		$(EMULATOR_DIR)/utils.h \
		$(EMULATOR_DIR)/ram.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/cpu.o $(EMULATOR_DIR)/cpu.c

$(OBJECTS_DIR)/emulator.o: $(EMULATOR_DIR)/emulator.c $(EMULATOR_DIR)/emulator.h \
		$(EMULATOR_DIR)/cpu.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(EMULATOR_DIR)/handler.h \
		$(EMULATOR_DIR)/enums.h \
		$(EMULATOR_DIR)/utils.h \
		$(EMULATOR_DIR)/ram.h \
		$(EMULATOR_DIR)/JSON.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/emulator.o $(EMULATOR_DIR)/emulator.c

$(OBJECTS_DIR)/handler.o: $(EMULATOR_DIR)/handler.c $(EMULATOR_DIR)/handler.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(EMULATOR_DIR)/enums.h \
		$(EMULATOR_DIR)/utils.h \
		$(EMULATOR_DIR)/ram.h \
		$(EMULATOR_DIR)/cpu.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/handler.o $(EMULATOR_DIR)/handler.c

$(OBJECTS_DIR)/ram.o: $(EMULATOR_DIR)/ram.c $(EMULATOR_DIR)/ram.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(EMULATOR_DIR)/utils.h \
		$(EMULATOR_DIR)/enums.h \
		$(EMULATOR_DIR)/cpu.h \
		$(EMULATOR_DIR)/handler.h \
		$(EMULATOR_DIR)/JSON.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/ram.o $(EMULATOR_DIR)/ram.c

$(OBJECTS_DIR)/utils.o: $(EMULATOR_DIR)/utils.c $(EMULATOR_DIR)/utils.h \
		$(EMULATOR_DIR)/motorolatypes.h \
		$(EMULATOR_DIR)/enums.h \
		$(EMULATOR_DIR)/ram.h \
		$(EMULATOR_DIR)/cpu.h \
		$(EMULATOR_DIR)/handler.h \
		$(EMULATOR_DIR)/JSON.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/utils.o $(EMULATOR_DIR)/utils.c

$(OBJECTS_DIR)/main.o: $(SOURCE_DIR)/main.cpp $(UI_DIR)/axolotlApp.h \
		$(UI_DIR)/editor.h \
		$(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(UI_DIR)/projectwizard.h \
		$(UI_DIR)/promanager.h \
		$(UI_DIR)/outputhighlighter.h \
		$(UI_DIR)/projectmanager.h \
		$(UI_DIR)/projecttreeitem.h \
		$(UI_DIR)/sourceadder.h \
		$(UI_DIR)/fileoptions.h \
		$(UI_DIR)/settingsmanager.h \
		$(UI_DIR)/uimemory.h \
		$(UI_DIR)/uistack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/main.o $(SOURCE_DIR)/main.cpp

$(OBJECTS_DIR)/completer.o: $(UI_DIR)/Completer/completer.cpp $(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(OBJECTS_DIR)/ui_completer.h \
		$(UI_DIR)/editor.h \
		$(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/Completer/completeritem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/completer.o $(UI_DIR)/Completer/completer.cpp

$(OBJECTS_DIR)/completeritem.o: $(UI_DIR)/Completer/completeritem.cpp $(UI_DIR)/Completer/completeritem.h \
		$(UI_DIR)/Completer/completerenums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/completeritem.o $(UI_DIR)/Completer/completeritem.cpp

$(OBJECTS_DIR)/completerparser.o: $(UI_DIR)/Completer/completerparser.cpp $(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/completerparser.o $(UI_DIR)/Completer/completerparser.cpp

$(OBJECTS_DIR)/axolotlApp.o: $(UI_DIR)/axolotlApp.cpp $(UI_DIR)/axolotlApp.h \
		$(UI_DIR)/editor.h \
		$(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h \
		$(UI_DIR)/projectwizard.h \
		$(UI_DIR)/promanager.h \
		$(UI_DIR)/outputhighlighter.h \
		$(UI_DIR)/projectmanager.h \
		$(UI_DIR)/projecttreeitem.h \
		$(UI_DIR)/sourceadder.h \
		$(UI_DIR)/fileoptions.h \
		$(UI_DIR)/settingsmanager.h \
		$(UI_DIR)/uimemory.h \
		$(UI_DIR)/uistack.h \
		$(OBJECTS_DIR)/ui_axolotlApp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/axolotlApp.o $(UI_DIR)/axolotlApp.cpp

$(OBJECTS_DIR)/configmanager.o: $(UI_DIR)/configmanager.cpp $(UI_DIR)/configmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/configmanager.o $(UI_DIR)/configmanager.cpp

$(OBJECTS_DIR)/editor.o: $(UI_DIR)/editor.cpp $(UI_DIR)/editor.h \
		$(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/Completer/completer.h \
		$(UI_DIR)/Completer/completerparser.h \
		$(UI_DIR)/Completer/completerenums.h \
		$(UI_DIR)/Completer/completerstructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/editor.o $(UI_DIR)/editor.cpp

$(OBJECTS_DIR)/editorhighlighter.o: $(UI_DIR)/editorhighlighter.cpp $(UI_DIR)/editorhighlighter.h \
		$(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/editorhighlighter.o $(UI_DIR)/editorhighlighter.cpp

$(OBJECTS_DIR)/fileoptions.o: $(UI_DIR)/fileoptions.cpp $(UI_DIR)/fileoptions.h \
		$(UI_DIR)/promanager.h \
		$(OBJECTS_DIR)/ui_fileoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/fileoptions.o $(UI_DIR)/fileoptions.cpp

$(OBJECTS_DIR)/outputhighlighter.o: $(UI_DIR)/outputhighlighter.cpp $(UI_DIR)/outputhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/outputhighlighter.o $(UI_DIR)/outputhighlighter.cpp

$(OBJECTS_DIR)/projectmanager.o: $(UI_DIR)/projectmanager.cpp $(UI_DIR)/projectmanager.h \
		$(UI_DIR)/projecttreeitem.h \
		$(UI_DIR)/promanager.h \
		$(UI_DIR)/sourceadder.h \
		$(UI_DIR)/fileoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/projectmanager.o $(UI_DIR)/projectmanager.cpp

$(OBJECTS_DIR)/projecttreeitem.o: $(UI_DIR)/projecttreeitem.cpp $(UI_DIR)/projecttreeitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/projecttreeitem.o $(UI_DIR)/projecttreeitem.cpp

$(OBJECTS_DIR)/projectwizard.o: $(UI_DIR)/projectwizard.cpp $(UI_DIR)/projectwizard.h \
		$(UI_DIR)/configmanager.h \
		$(UI_DIR)/promanager.h \
		$(OBJECTS_DIR)/ui_projectwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/projectwizard.o $(UI_DIR)/projectwizard.cpp

$(OBJECTS_DIR)/promanager.o: $(UI_DIR)/promanager.cpp $(UI_DIR)/promanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/promanager.o $(UI_DIR)/promanager.cpp

$(OBJECTS_DIR)/settingsmanager.o: $(UI_DIR)/settingsmanager.cpp $(UI_DIR)/settingsmanager.h \
		$(UI_DIR)/configmanager.h \
		$(OBJECTS_DIR)/ui_settingsmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/settingsmanager.o $(UI_DIR)/settingsmanager.cpp

$(OBJECTS_DIR)/sourceadder.o: $(UI_DIR)/sourceadder.cpp $(UI_DIR)/sourceadder.h \
		$(UI_DIR)/promanager.h \
		$(OBJECTS_DIR)/ui_sourceadder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/sourceadder.o $(UI_DIR)/sourceadder.cpp

$(OBJECTS_DIR)/themesetter.o: $(UI_DIR)/themesetter.cpp $(UI_DIR)/themesetter.h \
		$(UI_DIR)/configmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/themesetter.o $(UI_DIR)/themesetter.cpp

$(OBJECTS_DIR)/uimemory.o: $(UI_DIR)/uimemory.cpp $(UI_DIR)/uimemory.h \
		$(OBJECTS_DIR)/ui_uimemory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/uimemory.o $(UI_DIR)/uimemory.cpp

$(OBJECTS_DIR)/uistack.o: $(UI_DIR)/uistack.cpp $(UI_DIR)/uistack.h \
		$(OBJECTS_DIR)/ui_uistack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/uistack.o $(UI_DIR)/uistack.cpp

$(OBJECTS_DIR)/qrc_iconPack.o: $(OBJECTS_DIR)/qrc_iconPack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/qrc_iconPack.o $(OBJECTS_DIR)/qrc_iconPack.cpp

$(OBJECTS_DIR)/qrc_suggestions.o: $(OBJECTS_DIR)/qrc_suggestions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/qrc_suggestions.o $(OBJECTS_DIR)/qrc_suggestions.cpp

$(OBJECTS_DIR)/qrc_theme.o: $(OBJECTS_DIR)/qrc_theme.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/qrc_theme.o $(OBJECTS_DIR)/qrc_theme.cpp

$(OBJECTS_DIR)/moc_completer.o: $(OBJECTS_DIR)/moc_completer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_completer.o $(OBJECTS_DIR)/moc_completer.cpp

$(OBJECTS_DIR)/moc_completerparser.o: $(OBJECTS_DIR)/moc_completerparser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_completerparser.o $(OBJECTS_DIR)/moc_completerparser.cpp

$(OBJECTS_DIR)/moc_axolotlApp.o: $(OBJECTS_DIR)/moc_axolotlApp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_axolotlApp.o $(OBJECTS_DIR)/moc_axolotlApp.cpp

$(OBJECTS_DIR)/moc_editor.o: $(OBJECTS_DIR)/moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_editor.o $(OBJECTS_DIR)/moc_editor.cpp

$(OBJECTS_DIR)/moc_editorhighlighter.o: $(OBJECTS_DIR)/moc_editorhighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_editorhighlighter.o $(OBJECTS_DIR)/moc_editorhighlighter.cpp

$(OBJECTS_DIR)/moc_fileoptions.o: $(OBJECTS_DIR)/moc_fileoptions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_fileoptions.o $(OBJECTS_DIR)/moc_fileoptions.cpp

$(OBJECTS_DIR)/moc_outputhighlighter.o: $(OBJECTS_DIR)/moc_outputhighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_outputhighlighter.o $(OBJECTS_DIR)/moc_outputhighlighter.cpp

$(OBJECTS_DIR)/moc_projectmanager.o: $(OBJECTS_DIR)/moc_projectmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_projectmanager.o $(OBJECTS_DIR)/moc_projectmanager.cpp

$(OBJECTS_DIR)/moc_projecttreeitem.o: $(OBJECTS_DIR)/moc_projecttreeitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_projecttreeitem.o $(OBJECTS_DIR)/moc_projecttreeitem.cpp

$(OBJECTS_DIR)/moc_projectwizard.o: $(OBJECTS_DIR)/moc_projectwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_projectwizard.o $(OBJECTS_DIR)/moc_projectwizard.cpp

$(OBJECTS_DIR)/moc_settingsmanager.o: $(OBJECTS_DIR)/moc_settingsmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_settingsmanager.o $(OBJECTS_DIR)/moc_settingsmanager.cpp

$(OBJECTS_DIR)/moc_sourceadder.o: $(OBJECTS_DIR)/moc_sourceadder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_sourceadder.o $(OBJECTS_DIR)/moc_sourceadder.cpp

$(OBJECTS_DIR)/moc_uimemory.o: $(OBJECTS_DIR)/moc_uimemory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_uimemory.o $(OBJECTS_DIR)/moc_uimemory.cpp

$(OBJECTS_DIR)/moc_uistack.o: $(OBJECTS_DIR)/moc_uistack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/moc_uistack.o $(OBJECTS_DIR)/moc_uistack.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/stray68K/bin || mkdir -p $(INSTALL_ROOT)/opt/stray68K/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/stray68K/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/stray68K/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/stray68K/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:
